### ISSUE TITLE
Decimal separator is a coma

### ISSUE THREAD

**Issue by bigon** [bfrisque/ofxstatement-be-bnp#5]
Hello,

When I'm exporting the data from the Fortis website, the decimal separator is a coma.

That means that the conversion by the plugin is not going fine.

IIRC the website asked me once if I wanted a coma or a dot as a decimal separator, I cannot find any way to change that preference on the website.

I'm not too sure how it would be possible to auto detect format. If the coma or the dot is followed by strictly 2 digit it's the decimal separator otherwise it's a thousand one maybe?

**Comment by bfrisque** [comment]
Hello,

When downloading from BNP Paribas Fortis website, you can select either to download with dot or comma separator.

**Comment by bigon** [comment]
Hello,

The Fortis website has changed the way of exporting the data (again) and now you need to go via the "search transaction" page.

I exported the transaction from there and there was not option to select the separator.

It definitely uses a coma for that now in the CSV
